export default {
    TYPE_DATA_WEATHER:'TYPE_DATA_WEATHER',
    NET_WEATHER:'NET_WEATHER',
    TYPE_EATHER_FRESH:'TYPE_EATHER_FRESH',
    TYPE_NEWS_NET:'TYPE_NEWS_NET',
    TYPE_NEWS_FRESH:'TYPE_NEWS_FRESH',
}