export default {
    TYPE_DATA_WEATHER:'TYPE_DATA_WEATHER',
    NET_WEATHER:'NET_WEATHER',
    TYPE_EATHER_FRESH:'TYPE_EATHER_FRESH',
    TYPE_NEWS_NET:'TYPE_NEWS_NET',
    TYPE_NEWS_FRESH:'TYPE_NEWS_FRESH',
    TYPE_DATA_BOOK:'TYPE_DATA_BOOK',
    TYPE_BOOK_FRESH:'TYPE_BOOK_FRESH',
    TYPT_BOOK_NET:'TYPT_BOOK_NET'
}